# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JAWS-UG Kanazawa
email: jawsug.kanazawa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  JAWS-UG KANAZAWA のサイト
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jaws-ug-kanazawa.github.io" # the base hostname & protocol for your site
# twitter_username: nil
# github_username:  nil

# Build settings
markdown: kramdown
